apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-saver-ms
  name: location-saver-ms
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30006
  selector:
    service: location-saver-ms
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-saver-ms
  name: location-saver-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-saver-ms
  template:
    metadata:
      labels:
        service: location-saver-ms
    spec:
      containers:
        - image: ulyanov/location-saver-ms:latest
          name: location-saver-ms
          imagePullPolicy: Always
          env:
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kafka-locationsv-cm
                  key: KAFKA_URL
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-locationsv-cm
                  key: KAFKA_TOPIC
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-locsaver-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-locsaver-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-locsaver-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-locsaver-env
                  key: DB_PORT
      restartPolicy: Always
