apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer-ms
  name: location-producer-ms
spec:
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 30002
  selector:
    service: location-producer-ms
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer-ms
  name: location-producer-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer-ms
  template:
    metadata:
      labels:
        service: location-producer-ms
    spec:
      containers:
      - image: ulyanov/location-producer-ms:latest
        name: location-producer-ms
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-geolocations-cm
              key: KAFKA_SERVER
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-geolocations-cm
              key: KAFKA_TOPIC
      restartPolicy: Always
